#
# (C) Copyright 2020
# kmwebnet
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y += \
		cryptoauthlib/lib/hal/atca_hal.o \
		kdf.o \
		hal_uboot.o \
		hal_uboot_timer.o \
		configure.o \
		cryptoauthlib/lib/atca_cfgs.o \
		cryptoauthlib/lib/atca_command.o \
		cryptoauthlib/lib/atca_device.o \
		cryptoauthlib/lib/atca_execution.o \
		cryptoauthlib/lib/atca_iface.o \
		cryptoauthlib/lib/basic/atca_basic.o \
		cryptoauthlib/lib/basic/atca_basic_info.o \
		cryptoauthlib/lib/basic/atca_basic_read.o \
		cryptoauthlib/lib/basic/atca_basic_write.o \
		cryptoauthlib/lib/basic/atca_basic_lock.o \
		cryptoauthlib/lib/basic/atca_basic_genkey.o \
		cryptoauthlib/lib/basic/atca_basic_gendig.o \
		cryptoauthlib/lib/basic/atca_basic_random.o \
		cryptoauthlib/lib/basic/atca_basic_nonce.o \
		cryptoauthlib/lib/basic/atca_basic_sign.o \
		cryptoauthlib/lib/basic/atca_basic_verify.o \
		cryptoauthlib/lib/basic/atca_basic_aes.o \
		cryptoauthlib/lib/basic/atca_basic_kdf.o \
		cryptoauthlib/lib/crypto/atca_crypto_sw_sha2.o \
		cryptoauthlib/lib/crypto/hashes/sha2_routines.o \
		cryptoauthlib/lib/host/atca_host.o \
